server.port: 8080  
spring.profiles.active: dev 
spring.application.name: spider 
spring.batch.initializer.enabled: false
spring.batch.job.enabled: false
spring.batch.initialize-schema: always

--- 
spring.config.activate.on-profile: dev

spring.data.mongodb.authentication-database: admin
spring.data.mongodb.username: spider
spring.data.mongodb.password: spider
spring.data.mongodb.database: spider
spring.data.mongodb.port: 27017
spring.data.mongodb.host: localhost 

spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true 
       
logging.level.org.springframework.data: DEBUG
logging.level.org.springframework.security: ERROR 
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils: TRACE
logging.level.com.souljam.spider: INFO
 
#springdoc.api-docs.path: /api-docs
springdoc.swagger-ui.path: /swagger.html
springdoc.swagger-ui.operationsSorter: method

# Seconds, Minutes, Hours, Day of month, Month, Day of week, Year(Optional)
schedluer.job.cron: 0/30 * * * * ?

elasticsearch.host: 127.0.0.1
elasticsearch.port: 9300
elasticsearch.cluster_name: docker-cluster
spring.main.allow-bean-definition-overriding: true
--- 
spring.config.activate.on-profile: prd

spring.datasource.url: jdbc:mariadb://database:3306/spider?characterEncoding=UTF-8&amp;serverTimezone=UTC
spring.datasource.username: spider
spring.datasource.password: spider
spring.datasource.driver-class-name: org.mariadb.jdbc.Driver

spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false 
       
logging.level.org.springframework.data: ERROR
logging.level.org.springframework.security: ERROR 
logging.level.org.hibernate.SQL: ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: ERROR
logging.level.org.springframework.jdbc.core.JdbcTemplate: ERROR
logging.level.org.springframework.jdbc.core.StatementCreatorUtils: ERROR
logging.level.com.rock.jpetstore: ERROR

springdoc.swagger-ui.path: /swagger.html
springdoc.swagger-ui.operationsSorter: method

# Seconds, Minutes, Hours, Day of month, Month, Day of week, Year(Optional)
schedluer.job.cron: 0 0 0 1 * ?

elasticsearch.host: elasticsearch
elasticsearch.port: 9300
elasticsearch.cluster_name: docker-cluster
spring.main.allow-bean-definition-overriding: true